---
- hosts: controller
  tasks:
    - name: Add python38 support if needed
      block:
        - name: Ensure python3.8 is present
          become: true
          package:
            name: python3.8-dev
            state: present
      when:
        - ansible_os_family == "Debian"
        - ansible_test_python is version('3.8', '==')

    - name: Setup base virtualenv_options
      set_fact:
        _virtualenv_options: "--python python{{ ansible_test_python }}"

    - name: Prepare ara
      import_role:
        name: ara
        tasks_from: prepare_venv
      vars:
        ara_venv_path: ~/venv_ara

    - name: Create virtualenv for ansible-test
      shell: "virtualenv {{ _virtualenv_options }} ~/venv"

    - name: Install selinux into virtualenv
      shell: ~/venv/bin/pip install selinux
      when: ansible_os_family == "RedHat"

    - name: Install ansible into virtualenv
      shell: "~/venv/bin/pip install {{ ansible_user_dir }}/{{ zuul.projects['github.com/ansible/ansible'].src_dir }}"
