---
- hosts: controller
  tasks:
    - name: Add python38 support if needed
      block:
        - name: Ensure python3.8 is present
          become: true
          package:
            name: python3.8-dev
            state: present
      when:
        - ansible_os_family == "Debian"
        - ansible_test_python is version('3.8', '==')

    - name: Setup base virtualenv_options
      set_fact:
        _virtualenv_options: "--python python{{ ansible_test_python }}"

    - name: Create virtualenv for ansible-test
      shell: "virtualenv {{ _virtualenv_options }} ~/venv"

    - name: Install selinux into virtualenv
      shell: ~/venv/bin/pip install selinux
      when: ansible_os_family == "RedHat"

    - name: Install ara into virtualenv
      shell: ~/venv/bin/pip install "ara<1.0.0"

    - name: Install ansible into virtualenv
      shell: "~/venv/bin/pip install {{ ansible_user_dir }}/{{ zuul.projects['github.com/ansible-collection-migration/ansible-minimal'].src_dir }}"
      when: ansible_test_collections is defined

    - name: Install ansible into virtualenv
      shell: "~/venv/bin/pip install {{ ansible_user_dir }}/{{ zuul.projects['github.com/ansible/ansible'].src_dir }}"
      when: ansible_test_collections is not defined

    - name: Enable ARA callback plugin
      ini_file:
        path: "{{ ansible_user_dir }}/{{ zuul.projects['github.com/ansible/ansible'].src_dir }}/test/integration/{{ ansible_test_command }}.cfg"
        section: defaults
        option: callback_plugins
        value: "{{ ansible_user_dir }}/venv/lib/python{{ ansible_test_python}}/site-packages/ara/plugins/callbacks"

    - name: Enable persistent connection logging
      ini_file:
        path: "{{ ansible_user_dir }}/{{ zuul.projects['github.com/ansible/ansible'].src_dir }}/test/integration/{{ ansible_test_command }}.cfg"
        section: persistent_connection
        option: log_messages
        value: true

    - name: Set ansible log path
      ini_file:
        path: "{{ ansible_user_dir }}/{{ zuul.projects['github.com/ansible/ansible'].src_dir }}/test/integration/{{ ansible_test_command }}.cfg"
        section: defaults
        option: log_path
        value: ~/ansible-debug.txt
