---
- hosts: controller
  tasks:
    - import_role:
        name: ansible-test
      vars:
        ansible_test_test_command: "{{ ansible_test_command }}"
        ansible_test_location: "{{ ansible_user_dir }}/{{ zuul.projects['github.com/ansible/ansible'].src_dir }}"
        ansible_test_git_branch: "{{ zuul.projects['github.com/ansible/ansible'].checkout }}"
        ansible_test_test_collections: "{{ ansible_test_collections }}"
