---
- name: Set IPv4 nameservers
  set_fact:
    unbound_primary_nameserver: '{{ unbound_primary_nameserver_v4 }}'
    unbound_secondary_nameserver: '{{ unbound_secondary_nameserver_v4 }}'

- name: Include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yaml"
    - "{{ ansible_os_family }}.yaml"
    - "default.yaml"

- name: Ensure /etc/resolv.conf works before pulling packages
  become: true
  template:
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
    src: resolv.conf.j2

- name: Install the packages
  become: true
  package:
    name: "{{ unbound_packages }}"
    update_cache: true
    state: present

- when:
  - ansible_distribution == "Fedora"
  - ansible_distribution_major_version|int == 32
  block:
  - name: Enable updates
    copy:
      content: |
        [updates]
        name=Fedora $releasever - $basearch - Updates
        failovermethod=priority
        enabled=1
        repo_gpgcheck=0
        type=rpm
        gpgcheck=1
        metadata_expire=6h
        gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
        skip_if_unavailable=False
        metalink = https://mirrors.fedoraproject.org/metalink?repo=updates-released-f$releasever&arch=$basearch
      dest: /etc/yum.repos.d/fedora-updates.repo
    become: true

  - name: Workaround for https://github.com/ansible/ansible/issues/71528
    command: dnf upgrade --enablerepo=updates --advisory=FEDORA-2020-2faf839786
    become: true

  - name: Remove the updates repo
    file:
      path: /etc/yum.repos.d/fedora-updates.repo
      state: absent
    become: true

- name: Ensure Unbound conf.d directory exists
  become: true
  file:
    path: "{{ unbound_confd }}"
    state: directory

- name: Configure unbound forwarding
  become: true
  template:
    dest: "{{ unbound_confd }}/forwarding.conf"
    owner: root
    group: root
    mode: 0644
    src: forwarding.conf.j2
  notify:
    - Restart unbound

- name: Configure unbound TTL
  become: true
  template:
    dest: "{{ unbound_confd }}/ttl.conf"
    owner: root
    group: root
    mode: 0644
    src: ttl.conf.j2
  notify:
    - Restart unbound

- name: Update resolv.conf to localhost
  become: true
  copy:
    content: nameserver 127.0.0.1
    dest: /etc/resolv.conf

- name: Start unbound
  become: true
  service:
    name: unbound
    state: started
    enabled: true
