---
- hosts: controller
  tasks:
    - name: Setup tox role
      include_role:
        name: tox
      vars:
        tox_extra_args: -vv -- ansible-playbook -vvv playbooks/ansible-network-vmware-appliance/files/bootstrap.yaml
        tox_install_siblings: false
        zuul_work_dir: "{{ zuul.projects['github.com/ansible/ansible-zuul-jobs'].src_dir }}"
