---
- hosts: controller
  tasks:
    - name: Create inventory file
      import_role:
        name: ansible-test-inventory
      vars:
        ansible_test_inventory_os: vmware_rest
        ansible_test_inventory_dest: ~/inventory
        vmware_ci_set_passwords_secret_dir: '{{ zuul.executor.work_root }}'
    - name: Install ansible and deps to be able to prepare the env
      package:
        name:
          - ansible
          - python3-aiohttp
          - python3-pyvmomi
        state: present
      become: true
    - name: Install community.vmware and vmware.vmware_rest form Galaxy
      command: "ansible-galaxy collection install {{ item }}"
      with_items:
        - community.vmware
        - vmware.vmware_rest
