---
- hosts: controller
  gather_facts: false
  tasks:
    - shell: |
        export INVENTORY_PATH=/home/zuul/inventory
        source ~/{{ zuul.projects[ansible_collections_repo].src_dir }}/tests/integration/targets/init.sh
        ansible-playbook {{ downstream_ee_testing_targets[0] }}/prepare.yaml
        ansible-navigator run --eei brew.registry.redhat.io/{{ downstream_ee_image }} {{ downstream_ee_testing_targets[0] }}/run.yaml --mode=stdout --pull-policy=never --pass-environment-variable VMWARE_HOST --pass-environment-variable VMWARE_USER --pass-environment-variable VMWARE_PASSWORD --pass-environment-variable ESXI1_HOSTNAME --pass-environment-variable ESXI1_USERNAME --pass-environment-variable ESXI1_PASSWORD --pass-environment-variable VMWARE_VALIDATE_CERTS
      args:
        chdir: "~/{{ zuul.projects[ansible_collections_repo].src_dir }}/tests/integration/targets"
