---
- hosts: controller
  vars:
    log_dir: "{{ ansible_user_dir }}/zuul-output/logs/"
  tasks:
    - import_role:
        name: ara
        tasks_from: export
      vars:
        ara_venv_path: .tox/venv
        ara_export_dir: "{{ log_dir }}/controller/ara-report"
      always:
        - name: Copy ARA sqlite database
          shell: "cp {{ ansible_user_dir }}/.ara/ansible.sqlite {{ log_dir }}/controller/ara-report"

        # TODO: Migrate to fetch-zuul-logs when
        # https://review.openstack.org/#/c/583346/ is merged.
        - name: Collect log output
          no_log: true
          synchronize:
            dest: "{{ zuul.executor.log_root }}/"
            mode: pull
            src: "{{ log_dir }}"
            verify_host: true
