---
- hosts: controller
  tasks:
    - name: Ensure ara-report directory exists
      file:
        path: "{{ ansible_user_dir }}/zuul-output/logs/controller/ara-report"
        state: directory

    - block:
        - name: Generate ARA HTML output
          shell: ".tox/venv/bin/ara generate html {{ ansible_user_dir }}/zuul-output/logs/controller/ara-report"
          args:
            chdir: "{{ ansible_user_dir }}/{{ zuul.projects['github.com/ansible/ansible-zuul-jobs'].src_dir }}"
          environment:
            ARA_PLAYBOOK_PER_PAGE: 50

      always:
        - name: Copy ARA sqlite database
          shell: "cp {{ ansible_user_dir }}/.ara/ansible.sqlite {{ ansible_user_dir }}/zuul-output/logs/controller/ara-report"

        # TODO: Migrate to fetch-zuul-logs when
        # https://review.openstack.org/#/c/583346/ is merged.
        - name: Collect log output
          no_log: true
          synchronize:
            dest: "{{ zuul.executor.log_root }}/"
            mode: pull
            src: "{{ ansible_user_dir }}/zuul-output/logs/"
            verify_host: true
