---
- name: Disable vSphere-UI and reuse its memory
  shell: |
    cloudvm-ram-size -C 1000 vmware-sps
    cloudvm-ram-size -C 3000 vmware-vpxd
    cloudvm-ram-size -C 1024 vmware-stsd
    cloudvm-ram-size -C 200 observability
    cloudvm-ram-size -C 200 observability-vapi
    analytics
    cloudvm-ram-size -C 1 vsphere-ui
    systemctl disable vsphere-ui
  become: true
