---
- hosts: controller
  tasks:
    - name: Prepare the venv
      command: tox -e integration -vv --notest
      args:
        chdir: "{{ zuul.projects['github.com/ansible/network-ee'].src_dir }}"

    - name: Run integration tests
      args:
        chdir: "{{ zuul.projects['github.com/ansible/network-ee'].src_dir }}/tests/integration"
        executable: /bin/bash
      environment:
        TERM: xterm
      shell: "source ~/{{ zuul.projects['github.com/ansible/network-ee'].src_dir }}/.tox/integration/bin/activate; ansible-navigator"
