---
- hosts: all
  tasks:
    - name: Install gh cli
      become: true
      block:
        - name: add gh-cli repo
          shell: "dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo"

        - name: Install gh cli
          yum:
            name:
              - gh
            state: latest

    - set_fact:
        gh_token_path: "{{ ansible_user_dir }}/{{ zuul.projects['github.com/ansible/project-config'].src_dir }}/github_token_file.txt"

    - name: Copy github token into file
      copy:
        content: "{{ ansible_github_token.value }}"
        dest: "{{ gh_token_path }}"

  roles:
    - ensure-python
    - ensure-tox
