---
- hosts: all
  tasks:
    - name: Setup ensure-tox role
      include_role:
        name: ensure-tox

    - name: Setup tox role
      include_role:
        name: tox
      vars:
        tox_envlist: venv
        tox_extra_args: -vv --notest
        tox_install_siblings: false
        zuul_work_dir: "{{ zuul.projects['github.com/ansible-network/releases'].src_dir }}"

    - name: Fetch and install the artifacts
      import_role:
        name: deploy-artifacts
      vars:
        deploy_artifacts_venv_path: "~/{{ zuul.projects['github.com/ansible-network/releases'].src_dir }}/.tox/venv"
