---
- hosts: controller
  tasks:
    - name: Setup download-artifact-fork role
      include_role:
        name: download-artifact-fork
      vars:
        download_artifact_directory: "{{ zuul.projects['github.com/ansible/network-ee'].src_dir }}/_build/collections"
        download_artifact_type: ansible_collection

    - name: Adjust the requirements.yaml file to point on the local colletion tarballs
      replace:
        path: "{{ zuul.projects['github.com/ansible/network-ee'].src_dir }}/_build/requirements.yml"
        regexp: "{{ item.name }}$"
        replace: "collections/{{ item.url | basename }}"
      with_items: "{{ zuul.artifacts }}"
      when: "'metadata' in item and 'type' in item.metadata and (item.metadata.type == 'ansible_collection')"

    - name: Install podman
      package:
        name: podman
        state: present
      become: true

    - name: Build the image
      shell: |
        set -eux
        podman pull quay.io/ansible/ansible-runner:{{ ansible_runner_container_version }}
        podman pull quay.io/ansible/ansible-builder:latest
        podman pull quay.io/ansible/python-builder:latest

        ANSIBLE_GALAXY_CLI_COLLECTION_OPTS=""
        if [ ! "{{ ansible_runner_container_version }}" = "stable-2.9-devel" ]; then
          ANSIBLE_GALAXY_CLI_COLLECTION_OPTS="--pre"
        fi
        podman build . --pull-never --build-arg ANSIBLE_GALAXY_CLI_COLLECTION_OPTS=$ANSIBLE_GALAXY_CLI_COLLECTION_OPTS --build-arg EE_BASE_IMAGE=quay.io/ansible/ansible-runner:{{ ansible_runner_container_version }} --tag quay.io/ansible/network-ee:to-test
        podman build tests --pull-never --build-arg NETWORK_EE_IMAGE=quay.io/ansible/network-ee:to-test --tag quay.io/ansible/network-ee-tests:to-test
        podman build tests --pull-never --file Containerfile.ansible-test --target network-ee-unit-tests --build-arg NETWORK_EE_TESTS_IMAGE=quay.io/ansible/network-ee-tests:to-test --tag quay.io/ansible/network-ee-unit-tests:to-test
        podman build tests --pull-never --file Containerfile.ansible-test --target network-ee-sanity-tests --build-arg NETWORK_EE_TESTS_IMAGE=quay.io/ansible/network-ee-tests:to-test --tag quay.io/ansible/network-ee-sanity-tests:to-test
      args:
        chdir: "{{ zuul.projects['github.com/ansible/network-ee'].src_dir }}"
        
    - name: Install binary dependencies
      include_role:
        name: bindep
      vars:
        bindep_dir: "{{ zuul.project.src_dir }}"

    - set_fact:
        _network_appliance_groups: "{{ groups.keys()|select('match', '^(appliance|openvswitch)')|list }}"

    - name: Select proper ansible_network_os
      set_fact:
        _network_os: "{{ hostvars[groups[_network_appliance_groups|first][0]]['ansible_network_os'] }}"
      when: _network_appliance_groups|length > 0

    - name: Setup tox role
      include_role:
        name: tox
      vars:
        tox_envlist: venv
        tox_extra_args: "-vv -- ansible-playbook -v playbooks/ansible-test-network-integration-base/files/bootstrap-{{ _network_os }}.yaml"
        tox_install_siblings: false
        zuul_work_dir: "{{ zuul.projects['github.com/ansible/ansible-zuul-jobs'].src_dir }}"

    - name: Ensure remote NETCONF SSH host keys are known
      shell: "ssh-keyscan -v -t rsa -p 830 {{ hostvars[item].ansible_host }} >> ~/.ssh/known_hosts"
      when: hostvars[item].ansible_network_os in ['junos']
      with_inventory_hostnames: appliance

    - name: Create inventory file
      import_role:
        name: ansible-test-inventory
      vars:
        ansible_test_inventory_os: "{{ _network_os }}"
        ansible_test_inventory_dest: ~/inventory
        vmware_ci_set_passwords_secret_dir: '{{ zuul.executor.work_root }}'

    - name: Fetch and install the artifacts
      import_role:
        name: deploy-artifacts
      when:
        - ansible_test_collections | default(False)  
      
