---
- name: Run unit tests
  shell: "podman run --pull=never -w /usr/share/ansible/collections/ansible_collections/{{ collection_namespace }}/{{ collection_name }} {{ container_image_name }}-unit-tests:to-test"
