---
- hosts: all:!appliance*
  tasks:
    - name: Collect log output
      no_log: true
      synchronize:
        dest: "{{ zuul.executor.log_root }}/"
        mode: pull
        src: "{{ ansible_user_dir }}/zuul-output/logs/"
        verify_host: true
