---
- hosts: controller
  tasks:
    - name: Ensure tox
      include_role:
        name: ensure-tox

    - name: Setup tox role
      include_role:
        name: tox
      vars:
        tox_envlist: venv
        tox_extra_args: -vv -- ansible-playbook -v playbooks/ansible-network-junos-appliance/files/bootstrap.yaml
        tox_install_siblings: false
        zuul_work_dir: "{{ zuul.projects['github.com/ansible/ansible-zuul-jobs'].src_dir }}"
