---
# This file is a simplified version of a/playbooks/ansible-test-base/pre.yaml
# that should ultimately replace it.
- hosts: controller
  tasks:
    - name: Ensure controller directory exists
      file:
        path: "{{ ansible_user_dir }}/zuul-output/logs/controller"
        state: directory

    - name: Install container runtime
      include_role:
        name: ensure-podman
      when:
        - ansible_test_docker | default(False)

    - name: Run our-ensure-python role (Fedora only for now)
      include_role:
        name: our-ensure-python
      vars:
        ensure_python__version: "{{ ansible_test_python }}"

    - name: Create virtualenv for ansible-test
      shell: "python{{ ansible_test_python }} -mvenv ~/venv"

    - name: Install selinux into virtualenv
      shell: '~/venv/bin/pip install selinux'

    - name: Ensure pip temp directory exists in /var/tmp
      file:
        state: directory
        path: /var/tmp/ansible-test-pip

    - name: Install ansible into virtualenv
      # TODO(pabelanger): Remove ANSIBLE_SKIP_CONFLICT_CHECK in the future.
      environment:
        ANSIBLE_SKIP_CONFLICT_CHECK: 1
        TMPDIR: /var/tmp/ansible-test-pip
      shell: "~/venv/bin/pip install ~/{{ zuul.projects['github.com/ansible/ansible'].src_dir }}"
