---
- hosts: controller
  tasks:
    - name: Create virtualenv for ansible-navigator
      shell: virtualenv --python python3.8 ~/venv

    - name: Install ansible-navigator into virtualenv
      shell: "~/venv/bin/pip install ~/venv/bin/pip install {{ ansible_user_dir }}/{{ zuul.projects['github.com/ansible/ansible-navigator'].src_dir }}"
