---
- hosts: controller
  tasks:
    - name: config
      shell: mkdir -p ~/.config/ansible-navigator

    - name: copy
      shell: cp  ~/.ansible.cfg ~/.config/ansible-navigator/ansible.cfg

    - name: podman
      shell: podman pull quay.io/ansible/network-ee:latest

    - name: Run integration tests
      args:
        chdir: ~/.config/ansible-navigator
        executable: /bin/bash
      environment:
        TERM: xterm
      shell: "source ~/venv/bin/activate; ANSIBLE_CONFIG=ansible.cfg ansible-navigator run --eei quay.io/ansible/network-ee:latest ~/src/github.com/ansible-collections/arista.eos/tests/integration/site.yaml -i ~/inventory --mode=stdout -v"
