---
- project:
    check:
      jobs:
        - ansible-tox-py39:
            vars:
              tox_envlist: pytest,black
        - ansible-test-integration-ansible-plugin-builder:
            vars:
              ansible_test_collections: true
