---
- hosts: controller
  tasks:
    - name: Setup tox role
      include_role:
        name: tox
      vars:
        tox_envlist: venv
        tox_extra_args: -- ansible-playbook -v -c network_cli playbooks/ansible-network-nxos-appliance/files/bootstrap.yaml
        tox_install_siblings: false
        zuul_work_dir: "{{ zuul.projects['github.com/goneri/ansible-zuul-jobs'].src_dir }}"
