#!/usr/bin/env python3
#
# Copyright 2019-2020 Red Hat, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

import subprocess

import time


def set_new_pw():
    p = subprocess.Popen(['/usr/lib/vmware-vmdir/bin/vdcadmintool'], bufsize=1024,
                    stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    (child_stdin, child_stdout, child_stderr) = (p.stdin, p.stdout, p.stderr)

    buff = ''

    while True:
        p.poll()
        if p.returncode is not None:
            break
        line = child_stderr.read(1)
        buff += line.decode()
        if buff[-50:] == ' Get vmdir log level and mask\n==================\n\n':
            buff = ''
            child_stdin.write(b"3\n")
            child_stdin.flush()
        if buff[-50:] == '  Please enter account UPN : ':
            child_stdin.write(b"administrator@vsphere.local\n\n")
            child_stdin.flush()
            child_stdout.readline()
            new_pw = child_stdout.readline()
            return new_pw.decode().rstrip()

while True:
    new_pw = set_new_pw()
    if '"' not in new_pw and "'" not in new_pw:
        print(new_pw)
        exit(0)
    time.sleep(1)
