---
- name: Setup tox role
  include_role:
    name: tox
  vars:
    tox_envlist: venv
    tox_extra_args: -vv --notest
    tox_install_siblings: false
    zuul_work_dir: "{{ ansible_galaxy_importer_releases_dir }}"

- name: Fetch and install the artifacts
  import_role:
    name: deploy-artifacts
  vars:
    deploy_artifacts_venv_path: "{{ ansible_galaxy_importer_releases_dir }}/.tox/venv"
