---
- hosts: controller
  tasks:
    - name: Fetch govcsim
      get_url:
        url: https://github.com/vmware/govmomi/releases/latest/download/vcsim_Linux_x86_64.tar.gz
        dest: "{{ ansible_user_dir }}"
    - name: Expose vcsim in a directory from PATH
      command: "tar xfz {{ ansible_user_dir }}/vcsim_Linux_x86_64.tar.gz -C /usr/local/bin vcsim"
      become: true
    - name: Write the configuration for ansible-test
      import_role:
        name: ansible-test-provider
      vars:
        ansible_test_provider_name: vcenter
        ansible_test_provider_root_dir: "{{ ansible_user_dir }}/{{ zuul.projects['github.com/ansible/ansible'].src_dir }}"
        ansible_test_provider_test_with_vcsim: true
