---
- hosts: controller
  vars:
    ansible_test_location: "{{ ansible_user_dir }}/{{ zuul.projects[ansible_collections_repo].src_dir }}"
    ansible_coverage_report: "ansible-test coverage html"
    ansible_test_venv_path: "~/venv"
    ansible_test_collection_dir: "~/.ansible/collections/ansible_collections"
  tasks:
    - name: Copy the galaxy.yml on the controller
      fetch:
        src: "{{ ansible_test_location }}/galaxy.yml"
        dest: '{{ zuul.executor.work_root }}/tmp_fetch'
      register: _fetch
    - name: Load information from galaxy.yml
      include_vars:
        file: '{{ _fetch.dest }}'
        name: galaxy_info

    - name: Setup location of project for tests
      set_fact:
        test_location: "{{ ansible_test_collection_dir }}/{{ galaxy_info.namespace }}/{{ galaxy_info.name }}"

    - name: Coverage report for unit tests
      args:
        chdir: "{{ test_location }}"
        executable: /bin/bash
      environment: "{{ ansible_test_environment | default({}) }}"
      shell: "source {{ ansible_test_venv_path }}/bin/activate; {{ ansible_coverage_report }}"

    - name: Ensure controller directory exists
      file:
        path: "{{ ansible_user_dir }}/zuul-output/logs/controller"
        state: directory

    - name: Copy the coverage report
      shell: "cp -rfa {{ test_location }}/tests/output/reports/coverage {{ ansible_user_dir }}/zuul-output/logs/controller/"
