---
- name: Run target role
  include_role:
    name: "{{ item }}"

- name: Clear gathered facts
  ansible.builtin.meta: clear_facts

- name: Reset SSH connections
  ansible.builtin.meta: reset_connection

- name: Force meta handlers to run
  ansible.builtin.meta: flush_handlers
