---
- copy:
    src: list_all.py
    dest: /tmp/list_all.py
    mode: '0700'

- name: Identify all the targets
  command: python3 /tmp/list_all.py
  args:
    chdir: "{{ ansible_test_location }}"
  register: _result
- set_fact:
    ansible_test_splitter__targets_to_test: "{{ _result.stdout }}"
