---
- project:
    templates:
      - ansible-python-jobs
    check:
      jobs:
        - ansible-tox-py38:
            vars:
              tox_envlist: pytest,black
        - ansible-tox-py39:
            vars:
              tox_envlist: pytest,black
        - ansible-tox-py310:
            vars:
              tox_envlist: pytest,black
    gate:
      jobs:
        - ansible-tox-py38:
            vars:
              tox_envlist: pytest,black
        - ansible-tox-py39:
            vars:
              tox_envlist: pytest,black
    periodical:
      jobs:
        - downstream-ee-22-amazon-aws-s3_bucket
        - downstream-ee-22-amazon-aws-aws_s3
