---
- project:
    templates:
      - ansible-python-jobs
    check:
      jobs:
        - ansible-cloud-vcenter-appliance:
            files:
              - playbooks/ansible-cloud/vcenter-appliance/.*
              - playbooks/ansible-test-cloud-integration-base/.*
              - roles/vmware.*
        - ansible-network-asa-appliance:
            files:
              - playbooks/ansible-network-appliance-base/.*
              - playbooks/ansible-network-asa-appliance/.*
        - ansible-network-eos-appliance:
            files:
              - playbooks/ansible-network-appliance-base/.*
              - playbooks/ansible-network-eos-appliance/.*
        - ansible-network-ios-appliance:
            files:
              - playbooks/ansible-network-appliance-base/.*
              - playbooks/ansible-network-ios-appliance/.*
        - ansible-network-iosxr-appliance:
            files:
              - playbooks/ansible-network-appliance-base/.*
              - playbooks/ansible-network-iosxr-appliance/.*
        - ansible-network-junos-vqfx-appliance:
            files:
              - playbooks/ansible-network-appliance-base/.*
              - playbooks/ansible-network-junos-appliance/.*
            voting: false
        - ansible-network-junos-vsrx-appliance:
            files:
              - playbooks/ansible-network-appliance-base/.*
              - playbooks/ansible-network-junos-appliance/.*
        - ansible-network-nxos-appliance:
            files:
              - playbooks/ansible-network-appliance-base/.*
              - playbooks/ansible-network-nxos-appliance/.*
            voting: false
        - ansible-network-openvswitch-appliance:
            files:
              - playbooks/ansible-network-appliance-base/.*
              - playbooks/ansible-network-openvswitch-appliance/.*
        - ansible-network-vyos-appliance:
            files:
              - playbooks/ansible-network-appliance-base/.*
              - playbooks/ansible-network-vyos-appliance/.*
        - ansible-security-qradar-appliance:
            files:
              - playbooks/ansible-test-network-integration-base/files/bootstrap-qradar.yaml
              - playbooks/ansible-network-appliance-base/.*
        - ansible-security-splunk-appliance:
            files:
              - playbooks/ansible-test-network-integration-base/files/bootstrap-splunk.yaml
              - playbooks/ansible-network-appliance-base/.*
              - roles/splunk.*
        - ansible-security-trendmicro-deepsec-appliance:
            files:
              - playbooks/ansible-test-network-integration-base/files/bootstrap-trendmicro.yaml
              - playbooks/ansible-network-appliance-base/.*


    gate:
      jobs:
        - ansible-cloud-vcenter-appliance:
            files:
              - playbooks/ansible-cloud/vcenter-appliance/.*
              - playbooks/ansible-test-cloud-integration-base/.*
              - roles/vmware.*
        - ansible-network-asa-appliance:
            files:
              - playbooks/ansible-network-appliance-base/.*
              - playbooks/ansible-network-asa-appliance/.*
        - ansible-network-eos-appliance:
            files:
              - playbooks/ansible-network-appliance-base/.*
              - playbooks/ansible-network-eos-appliance/.*
        - ansible-network-ios-appliance:
            files:
              - playbooks/ansible-network-appliance-base/.*
              - playbooks/ansible-network-ios-appliance/.*
        - ansible-network-iosxr-appliance:
            files:
              - playbooks/ansible-network-appliance-base/.*
              - playbooks/ansible-network-iosxr-appliance/.*
        - ansible-network-junos-vsrx-appliance:
            files:
              - playbooks/ansible-network-appliance-base/.*
              - playbooks/ansible-network-junos-appliance/.*
        - ansible-network-openvswitch-appliance:
            files:
              - playbooks/ansible-network-appliance-base/.*
              - playbooks/ansible-network-openvswitch-appliance/.*
        - ansible-network-vyos-appliance:
            files:
              - playbooks/ansible-network-appliance-base/.*
              - playbooks/ansible-network-vyos-appliance/.*
        - ansible-security-qradar-appliance:
            files:
              - playbooks/ansible-network-appliance-base/.*
        - ansible-security-splunk-appliance:
            files:
              - playbooks/ansible-test-network-integration-base/files/bootstrap-splunk.yaml
              - playbooks/ansible-network-appliance-base/.*
              - roles/splunk.*
        - ansible-security-trendmicro-deepsec-appliance:
            files:
              - playbooks/ansible-network-appliance-base/.*
