---
- project:
    templates:
      - ansible-python-jobs
    check:
      jobs:
        - ansible-cloud-vcsa-appliance
        - ansible-network-eos-appliance
        - ansible-network-ios-appliance
        - ansible-network-iosxr-appliance
        - ansible-network-junos-appliance
        - ansible-network-nxos-appliance:
            voting: false
        - ansible-network-openvswitch-appliance
        - ansible-network-vyos-appliance
        - ansible-test-cloud-integration-vcsa-python36:
            vars:
              ansible_test_integration_target: vcenter_folder

    gate:
      jobs:
        - ansible-cloud-vcsa-appliance
        - ansible-network-eos-appliance
        - ansible-network-ios-appliance
        - ansible-network-iosxr-appliance
        - ansible-network-junos-appliance
        - ansible-network-openvswitch-appliance
        - ansible-network-vyos-appliance
