---
- project:
    templates:
      - ansible-python-jobs
      - ansible-collections-amazon-aws-each-target
    check:
      jobs:
        - build-ansible-collection
        - integration-amazon.aws-target-aws_caller_info
        - ansible-tox-py38:
            vars:
              tox_envlist: pytest,black
        - ansible-tox-py39:
            vars:
              tox_envlist: pytest,black
        - ansible-tox-py310:
            vars:
              tox_envlist: pytest,black
    gate:
      jobs:
        - ansible-tox-py38:
            vars:
              tox_envlist: pytest,black
        - ansible-tox-py39:
            vars:
              tox_envlist: pytest,black
    periodic:
      jobs:
        - ansible-test-splitter
        - integration-amazon.aws-target-aws_caller_info
