---
- hosts: all
  tasks:
    - name: Build downstream collection
      shell: "source ~/venv/bin/activate; make downstream-build"
      args:
        chdir: "{{ zuul.projects['github.com/openshift/community.okd'].src_dir }}"
      environment:
        DOWNSTREAM_BUILD_PYTHON: "python"
        INSTALL_DOWNSTREAM_COLLECTION_PATH: "{{ downstream_collections_path }}"
