---
- hosts: controller
  tasks:
    - name: Run ansible-test
      import_role:
        name: ansible-test
      vars:
        ansible_test_test_command: "{{ ansible_test_command }}"
        ansible_test_venv_path: "~/venv"
        ansible_test_location: "{{ downstream_collections_path }}/redhat/openshift"
