---
- hosts: all
  tasks:
    - name: Ensure artifacts directory exists
      file:
        path: "{{ ansible_user_dir }}/zuul-output/artifacts"
        state: directory

    - name: Copy the tarballs to the artifacts directory
      shell: |
       cp -v src/{{ zuul.project.canonical_name }}/dist/*.tar.gz {{ ansible_user_dir }}/zuul-output/artifacts
       cp -v src/{{ zuul.project.canonical_name }}/dist/*.whl {{ ansible_user_dir }}/zuul-output/artifacts
