---
- hosts: all
  tasks:
    - name: Install container runtime
      include_role:
        name: "ensure-{{ (container_command == 'docker') | ternary('docker', 'podman') }}"

    - name: Run buildset registry (if not already running)
      when: buildset_registry is not defined
      include_role:
        name: run-buildset-registry

    - name: Use buildset registry
      include_role:
        name: use-buildset-registry
